### ISSUE TITLE
Add more capabilities to archiver

### ISSUE THREAD

**Issue by billdback-ts** [thoughtspot/cs_tools#22]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Archiver is a great tool, but there are some thing that would be nice to have.  

1. Add the ability to check lower in the dependency tree,e.g. worksheets and tables for stuff that isn't being used.  This could be based on dependencies, so a table that has a worksheet that has content no one has viewed in a while.
2. Add ability to check worksheets and tables for ones that aren't being searched.
3. Isolate based on group(s) or users(0) to find their old content.

**Comment by boonhapus** [comment]
Looking through old issues.. some thoughts here.

1. This is possible, but I'm unsure how useful it would be. What's the selection criteria here, if ANY activity has happened on a Worksheet's dependents? I think the best strategy for this option is to `--dry-run` dump to a Syncer (which didn't exist at the time this issue was opened) and then bash it up against `TS_DEPENDENT_OBJECT` in the Searchable tool. Also as part of v1.4.0 (#39), we're exploring a new tool which will bulk tag objects in your platform and interactive nicely with Syncers. This could achieve the more flexible requirements in content isolation for Archiver.

2. This is not possible. **ThoughtSpot** does not expose which data source is being Searched against, so we cannot programmatically determine this.

3. If this is an `AND` filter on top of other criteria in `identify`? I think that's relatively easy to implement.

**Comment by boonhapus** [comment]
This is resolved as part of V1.4.0 , check our documentation to learn more.

https://thoughtspot.github.io/cs_tools/tools/archiver/

![img](https://raw.githubusercontent.com/thoughtspot/cs_tools/gh-pages/terminal-screenshots/cs_tools_tools_archiver_identify___help.svg)
