### ISSUE TITLE
Warning about the breaking changes in Scriptability

### ISSUE THREAD

**Issue by mezig351** [thoughtspot/cs_tools#38]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

We are interested in using scriptability in our version controlling workflows, and believe it can meet most of our needs. We were just slightly concerned about the warning

```
USE AT YOUR OWN RISK!

This tool uses private API calls! These could change with any version update and break the provided functionality.
```

In case of breaking changes to the ThoughtSpot APIs, how could we get an early warning and how soon would `cs_tools` catch up? What would you recommend to those who wish to use this product in production systems?

Best,

**Comment by boonhapus** [comment]
Hi @mezig351 !

This warning happens because we are utilizing a private API call for support TS Software v7.1.1. We are soon dropping support for 7.1.1 to stay in line with the engineering department's guideline of minimum supported version of SW 7.2.1.

In 7.2.1 , we leverage a public API endpoint and this warning goes away. This change is targeted for CS Tools 1.4.0 which is sometime in the next couple of months.

All this said, we test CS Tools against the latest Cloud/SaaS build and the Scriptability tool still works utilizing that private API call -- it has not changed since then.

\- SN
