### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by strainger** [thoughtspot/cs_tools#41]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

What are some bare system requirements for running a dedicated system for CS Tools? I'm wondering about filesystem partitioning, RAM/CPU, etc. In looking on the documentation all I could find in terms of requirements is that the server must be running Python v3.6.8 or later. Thank you all so much.

**Comment by boonhapus** [comment]
Hey @strainger! 👋 

Python 3.6.7+ is really the only requirement. The tools essentially just leverage the [__ThoughtSpot__ REST APIs](https://developers.thoughtspot.com/docs/?pageid=rest-api-reference) and many packages from the python ecosystem.

For example, I have the tools ([Searchable](https://thoughtspot.github.io/cs_tools/cs-tools/searchable/) `gather` and `bi_server`) running nightly against our internal __ThoughtSpot__ Cloud cluster. The tools from run a standard AWS T2.Micro that's always-on since it operates as one of my ETL servers.

Hope this helps!

---

### Longer, boring background answer

The reason why we don't recommend running the tools from the ThoughtSpot cluster itself is two-fold.

**Memory Pressure**
In the current version, the Searchable tool is vulnerable to memory-constrained environments. We do a silly thing and hold much of the metadata object model in memory until it's time to dump to a Syncer.

_In most cases_, this is not a problem as most __ThoughtSpot__ environments don't grow to be massive. However, this is not true for some of our Fortune 10 or OEM customers who are running the tools. 😄 They've shown me how naïve of an approach the in-memory route can be.

**Environment Isolation**
This is just a good practice to follow, _"don't run auxiliary scripts in your production environments"_. Because software is developed by humans, if -- for whatever reason -- we accidentally botch the install or critically impact the system, we don't want that to happen on your production __ThoughtSpot__ cluster (ie, the ones your users are accessing!).

There's no possibility of python environment contamination, because the CS Tools bootstrapper will create and manage its own virtual environment. We then symlink to the executable inside that venv so you can access the `cs_tools` command without ever needing to know about the isolated environment.

**Comment by boonhapus** [comment]
Closing as this has been answered. Please re-open, or start a Discussion if you want more information!
